TicTacToe.Web/Models/ErrorViewModel.cs
using System;

namespace TicTacToe.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TicTacToe.Web/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using TicTacToe.Models.Entity;
using TicTacToe.Models.MVC.Game;
using TicTacToe.Services;
using TicTacToe.Web.Models;
using Game = TicTacToe.Models.MVC.Game.Game;
using Level = TicTacToe.Models.MVC.Game.Level;
using Player = TicTacToe.Models.MVC.Game.Player;

namespace TicTacToe.Web.Controllers
{
    public class GameController : Controller
    {
        private readonly ILogger<GameController> _logger;
        private readonly IUserService _userService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IGameService _gameService;
        private readonly IGameCellService _gameCellService;

        public User CurrentUser
        {
            get
            {
                var remoteIpAddress = _httpContextAccessor.HttpContext.Connection.RemoteIpAddress;
                var user = _userService.FindByIp(remoteIpAddress.ToString());
                if (user == null)
                {
                    _userService.Create(remoteIpAddress.ToString());
                    user = _userService.FindByIp(remoteIpAddress.ToString());
                }

                return user;
            }
        }

        public GameController(ILogger<GameController> logger, IUserService userService,
            IHttpContextAccessor httpContextAccessor, IGameService gameService, IGameCellService gameCellService)
        {
            _logger = logger;
            _userService = userService;
            _httpContextAccessor = httpContextAccessor;
            _gameService = gameService;
            _gameCellService = gameCellService;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Index()
        {
            var currentGame = _gameService.GetCurrentGame(CurrentUser.Ip);
            return View(currentGame);
        }

        public IActionResult Results()
        {
            return NoContent();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var context = HttpContext.Features.Get<IExceptionHandlerFeature>();
            var exception = context?.Error; // Your exception

            if (exception != null)
            {
                _logger.LogError(exception.Message);
                if (exception.InnerException != null)
                    _logger.LogError(exception.InnerException.Message);

            }
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult StartGame(Game game)
        {
            if (!ModelState.IsValid)
                return View("Index", game);
            var newGame = _gameService.Create(CurrentUser.Id, game.Player, game.Level);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult StopGame(Game game)
        {
            _gameService.Stop(game.Id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult AjaxMakePlayerMove(int gameId, int cellId)
        {
            _gameService.MakePlayerMove(gameId, cellId);
            return PartialView("GameGridPartial", CreateGameCellsList(gameId));
        }
        [HttpPost]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult AjaxMakeComputerMove(int gameId)
        {
            _gameService.MakeComputerMove(gameId);
            return PartialView("GameGridPartial", CreateGameCellsList(gameId));
        }
        [HttpPost]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult UpdateGameInfo(int gameId)
        {
            var currentGame = _gameService.GetGame(gameId);
            return PartialView("GameInfoPartial", currentGame);
        }
        private IList<GameCell> CreateGameCellsList(int gameId)
        {
            return _gameCellService.GetAll(gameId);
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

TicTacToe.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using TicTacToe.Web.Models;

namespace TicTacToe.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TicTacToe.Web/Controllers/ResultsController.cs
using Microsoft.AspNetCore.Mvc;
using TicTacToe.Services;

namespace TicTacToe.Web.Controllers
{
    public class ResultsController : Controller
    {
        private readonly IResultsService _resultsService;

        public ResultsController(IResultsService resultsService)
        {
            _resultsService = resultsService;
        }
        public IActionResult Index()
        {
            var results = _resultsService.GetResults();
            return View(results);
        }
    }
}

TicTacToe.Web/Views/Game/CreateOrUpdatePlayerPartial.cshtml
@using TicTacToe.Resources
@model TicTacToe.Models.MVC.Game.Game
<div class="form-row justify-content-center">
    <div class="form-group">
        <input type="hidden" asp-for="Player.Id" />
        <label>@GameStrings.InputUserName:</label>
        <div class="input-group mb-1">
            <input type="text" class="form-control text-center" asp-for="Player.Name" aria-describedby="basic-addon3">
        </div>
        <span asp-validation-for="Player"></span>
    </div>
</div>
<div class="form-row justify-content-center">
    <div class="form-group m-1">
        <label class="mb-3">@GameStrings.SelectGameSide:</label>
        <div class="btn-group mt-2" role="group">
            <div class="form-check m-1  text-center">
                @Html.EditorFor(m => m.Player.GameSideEnum, "EnumRadioButtonList")
            </div>
        </div>
        <span asp-validation-for="Player.GameSideEnum"></span>
    </div>
</div>

TicTacToe.Web/Views/Game/CreatePlayerPartial.cshtml
@using TicTacToe.Resources
@model TicTacToe.Models.MVC.Game.Player
<form id="userInfoForm" class="row" asp-action="CreatePlayer" asp-controller="Game" method="POST">
    <div class="col text-center h-25">
        <div class="form-group">
            <div class="col text-center">
                <label>@GameStrings.InputUserName:</label>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" asp-for="Name" aria-describedby="basic-addon3">
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col text-center">
                <label>@GameStrings.SelectGameSide:</label>
                <div class="btn-group m-1" role="group">
                    <div class="form-check m-1">
                        @Html.EditorFor(m => m.GameSide, "EnumRadioButtonList")
                    </div>

                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-dark m-3">@GameStrings.PlayButton</button>
    </div>
</form>

TicTacToe.Web/Views/Game/GameGridPartial.cshtml
@using TicTacToe.Models.MVC.Game
@using TicTacToe.Resources
@model IList<TicTacToe.Models.MVC.Game.GameCell>
<form id="gameForm" class="row justify-content-center px-lg-5">

    <div class="col-8  px-lg-5">
        @for (var index = 1; index < 4; index++)
        {
        var row = Model.Where(d=>d.Cell.Name.Contains($"{index}."));
            <div class="row">
                @foreach(var cell in row)
                {
                    <div class="col-4  border border-dark">
                        <div class="box text-center">
                            <input type="hidden" asp-for="@cell.CellId" />
                            <input type="hidden" asp-for="@cell.GameId" />
                            @if (cell.GameSide == null)
                            {
                                <a class="empty-cell" href="@(Model.Any(s => s.IsHighlighted) ? "" : "javascript:void(0)")">
                                    <img src="images/empty_cell.svg" />
                                </a>
                            }
                            else
                            {
                                if (cell.GameSide == GameSideEnum.Crosses)
                                {
                                    
                                    if (!cell.IsHighlighted)
                                    {
                                        <img class="cross-cell" src="images/cross.svg" />
                                    }
                                    else
                                    {
                                        <img class="cross-cell" src="images/cross_highlighted.svg" />
                                    }
                                }
                                else
                                {
                                  
                                    if (!cell.IsHighlighted)
                                    {
                                        <img class="zero-cell" src="images/zero.svg" />
                                    }
                                    else
                                    {
                                        <img class="zero-cell" src="images/zero_highlighted.svg" />
                                    }
                                }
                            }
                        </div>
                    </div>
                }
            </div>
        
        }
    </div>

</form>

TicTacToe.Web/Views/Game/GameInfoPartial.cshtml
@using TicTacToe.Resources
@model TicTacToe.Models.MVC.Game.Game
<form id="gameInfoForm" class="row h-25"  method="POST">
    <div class="col text-center ">
        <div class="form-group">
            <div class="col text-center">
                <input type="hidden" asp-for="Id"/>
                <label>@(GameStrings.GameStartLabel): @Model.StartDateTime?.ToShortDateString() @Model.StartDateTime.Value.ToLongTimeString()</label>
                <input type="hidden" asp-for="StartDateTime"/>
            </div>
        </div>
        <div class="form-group">
            @if (Model.EndDateTime == null)
            {
                <div class="col text-center">
                    <input type="hidden" asp-for="Player.Id" />
                    <label>@(GameStrings.PlaysLabel): @(Model.Player.Name) vs PC</label>
                </div>
            }
            else
            {
                <div class="col text-center">
                    <label>@(GameStrings.EndGameLabel): @Model.EndDateTime?.ToShortDateString() @Model.EndDateTime.Value.ToLongTimeString()</label>
                    <br/>
                    @if (Model.WinnerPlayer != null)
                    {

                <label>@(GameStrings.WonLabel): @(Model.WinnerPlayer.Name)</label>

                    }
                    else
                    {
                        <label>@(GameStrings.Result): @GameStrings.Tie</label>
                    }
                </div>
                <button class="btn btn-success m-3" type="submit" asp-action="Index" asp-controller="Game">@GameStrings.PlayAgain</button>
            }
        </div>
        @if (Model.EndDateTime == null)
        {
            <button id="stopGameButton" type="submit" asp-action="StopGame" asp-controller="Game" class="btn btn-danger m-3">@GameStrings.StopGameButton</button>
        }
    </div>
</form>

TicTacToe.Web/Views/Game/Index.cshtml
@using TicTacToe.Resources
@model TicTacToe.Models.MVC.Game.Game
@{
    ViewData["Title"] = GameStrings.PlayPageTitle;
}

<div class="container">
    <div class="col justify-content-center text-center">
        @if (Model.StartDateTime == null)
        {
            <form id="userInfoForm" class="container" asp-action="StartGame" asp-controller="Game" method="POST">
                <partial name="CreateOrUpdatePlayerPartial" />
                <partial name="LevelPartial" />
                <button type="submit" class="btn btn-dark m-1">@GameStrings.PlayButton</button>
            </form>
        }
        else
        {
            <partial name="GameInfoPartial" model="@Model" />
            <partial name="GameGridPartial" model="@Model.GameCells" />
        }
    </div>

</div>

@section Scripts
{
    <script type="text/javascript">
        $(function () {
            TicTacToe.Views.Game.Init({
                MakePlayerMoveUrl: '@Url.Action("AjaxMakePlayerMove")',
                MakeComputerMoveUrl: '@Url.Action("AjaxMakeComputerMove")',
                UpdateGameInfoUrl: '@Url.Action("UpdateGameInfo")'
            });
        });
    </script>
}

TicTacToe.Web/Views/Game/LevelPartial.cshtml
@using TicTacToe.Resources
@model TicTacToe.Models.MVC.Game.Game
<div class="form-row justify-content-center">
    <div class="form-group">
        <label class="mb-3">@GameStrings.SelectGameLevel:</label>
        <div class="btn-group mt-2" role="group">
            <div class="form-check m-1">
                @Html.EditorFor(m => m.Level.LevelEnum, "EnumRadioButtonList")
            </div>
        </div>
        <span asp-validation-for="Level.LevelEnum"></span>
    </div>
</div>
@section Scripts
{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TicTacToe.Web/Views/Results/Index.cshtml
@using TicTacToe.Models.MVC.Game
@using TicTacToe.Resources
@model TicTacToe.Models.MVC.Results.Results
@{
    ViewData["Title"] = ResultsStrings.ResultsPageTitle;
}

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">№</th>
                <th scope="col">@ResultsStrings.StartColumn</th>
                <th scope="col">@ResultsStrings.PlayerColumn</th>
                <th scope="col">@ResultsStrings.GameSideColumn</th>
                <th scope="col">@ResultsStrings.ResultTitle</th>
                <th scope="col">@ResultsStrings.EndColumn</th>
            </tr>
        </thead>
        <tbody>
            @for (var index = 0; index < Model.GameResults.Count(); index++)
            {
                var game = Model.GameResults[index];
                <tr>
                    <th scope="row">@(index+1)</th>
                    <td>@game.StartDateTime.ToShortDateString() @game.StartDateTime.ToLongTimeString()</td>
                    <td>@game.Player.Name</td>
                    <td>@if (game.Player.GameSideEnum == GameSideEnum.Crosses)
                        {
                            @ResultsStrings.Crosses
                        }
                        else
                        {
                            @ResultsStrings.Zeros
                        }</td>
                    <td>
                        @if (game.WinnerPlayer == null)
                        {
                            @ResultsStrings.Tie
                        }
                        else
                        {
                            @game.WinnerPlayer?.Name
                        }
                    </td>
                    <td>@game.EndDateTime?.ToShortDateString() @game.EndDateTime?.ToLongTimeString()</td>
                </tr>
            }
        </tbody>
    </table>

</div>

@section Scripts
{
    @*<script type="text/javascript">
            $(function () {
                TicTacToe.Views.Results.Init({

                });
            });
        </script>*@
}

TicTacToe.Web/Views/Shared/EditorTemplates/EnumRadioButtonList.cshtml
@model Enum

@{
   
     // Looks for a [Display(Name="Some Name")] or a [Display(Name="Some Name", ResourceType=typeof(ResourceFile)] Attribute on your enum
    Func<Enum, string> getDescription = en =>
    {
        Type type = en.GetType();
        System.Reflection.MemberInfo[] memInfo = type.GetMember(en.ToString());

        if (memInfo != null && memInfo.Length > 0)
        {

            object[] attrs = memInfo[0].GetCustomAttributes(typeof(System.ComponentModel.DataAnnotations.DisplayAttribute),
                                                            false);

            if (attrs != null && attrs.Length > 0)
                return ((System.ComponentModel.DataAnnotations.DisplayAttribute)attrs[0]).GetName();
        }

        return en.ToString();
    };
    var listItems = Enum.GetValues(Model.GetType()).OfType<Enum>().Select(e =>
    new SelectListItem()
    {
        Text = getDescription(e),
        Value = e.ToString(),
        Selected = e.Equals(Model)
    }).Where(t=>t.Value!="None");
    string prefix = ViewData.TemplateInfo.HtmlFieldPrefix;
    int index = 0;
    ViewData.TemplateInfo.HtmlFieldPrefix = string.Empty;
    
    foreach (var li in listItems)
    {
        string fieldName = string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0}_{1}", prefix, index++);
        
            <label class="label_radio" for="@fieldName">
                @Html.RadioButton(prefix, li.Value, li.Selected, new { @id = fieldName })
                @li.Text
            </label>
        
    }
    ViewData.TemplateInfo.HtmlFieldPrefix = prefix;
}

TicTacToe.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@using TicTacToe.Resources
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tic-Tac-Toe</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Game" asp-action="Index">Tic-Tac-Toe</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">@GameStrings.PlayMenuButtonTitle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Results" asp-action="Index">@GameStrings.ResultsMenuButtonTitle</a>
                        </li>
                    </ul>
                </div>
                <div class="nav-tabs text-right justify-content-lg-end">
                    @await Html.PartialAsync("_SelectLanguagePartial")
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Tic-Tac-Toe
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/game.js" asp-append-version="true"></script>
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TicTacToe.Web/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Game" 
          asp-action="SetLanguage" asp-route-returnUrl="@returnUrl" 
          method="post" class="form-group" role="form">
        <label asp-for="@requestCulture.RequestCulture.UICulture.Name">@Localizer["Language:"]</label> <select name="culture"
                                                                                                               onchange="this.form.submit();"
                                                                                                               asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
        </select>
    </form>
</div>